### ISSUE TITLE
Sorting a collection

### ISSUE THREAD

**Issue by ashmore11** [siegesmund/SwiftDDP#23]
Hi There,

I can't seen to find a way of sorting my collection. I know collection.sorted returns all the values in my collection, sorted by id, but I would like to sort using another field in my collection.

Is there a built in way of doing this?

Thanks!

**Comment by siegesmund** [comment]
No, there is not. This is intentional. MeteorJS is tied to MongoDB on both the client and server. There's nothing approximating MongoDB in iOS, and for serious applications you'll really want to use Core Data, Realm or perhaps Couchbase Mobile as a backend. 

MeteorCollection is intended to provide scaffolding to create more powerful collections backed by other datastores by providing a built-in object that responds to server changes. While it has a few convenience methods, it's not a full-fledged client datastore like minimongo.

That said, what you're trying to do is super easy. Just subclass MeteorCollection and add a method that does what you're trying to do. Have a look at the MeteorCollection [code](https://github.com/siegesmund/SwiftDDP/blob/master/SwiftDDP/MeteorCollection.swift) to get an idea of how it works. It's really not complicated.

**Comment by ashmore11** [comment]
Ok thanks @siegesmund, I'll give it a go today : ) thanks!
