### ISSUE TITLE
Not getting default collection on server "users"

### ISSUE THREAD

**Issue by Sadmansamee** [siegesmund/SwiftDDP#33]
I'm getting collection data  from server by with "AbstractCollection" way.

 I can get all  the collection data for other subscription but when I subscribe a "Subscription" named "userList" that holds a meteor default collection "users" but however "**documentWasAdded**","**documentWasChanged**" is **not getting called**. But I can see those value coming on LOG. 
Is that problem with default collection?

**Comment by siegesmund** [comment]
You should be able to to subscribe to the default users collection, just like other collections.

**Comment by Sadmansamee** [comment]
But I wasn't getting, I was having trouble only with this sub,strange.

**Comment by siegesmund** [comment]
What are you trying to subscribe to? i.e., what name string are you passing to subscribe function?

**Comment by Sadmansamee** [comment]
I was trying to subscribe "userList" Subscription that has "users" collection.

**Comment by esaounkine** [comment]
@Sadmansamee how was it published on the server? 
Often times in order to avoid publishing `users` to everyone, the publication function includes a condition to check whether current user has access rights or to only fetch a single user.
So it might depend on whether:
- you have signed in
- have proper rights
prior to subscribing to the `users` collection.

**Comment by zahedul** [comment]
@siegesmund  ... will you please close this issue. getting users collection is going good
