### ISSUE TITLE
CoreData example not working

### ISSUE THREAD

**Issue by antonioandrade** [siegesmund/SwiftDDP#40]
I've been playing around with SwiftDDP and quickly got it working to some extent. However I'm still to make the CoreData integration to function properly. 

After a couple of frustrating trials I went back to the CoreData example and it only seems to work against an old version of the Todos app (`https://github.com/meteor/todos` at commit `4ad2706f88f7d6ad9059a52fd0a13f3442a57cca`, where it's still using the _privateLists_ subscription name so I assume that's the tested one).

Any ideas of why the CoreData Example is not working on the latest Todo version, at least as far as receiving entries from the server? 
Updating the subscription names didn't help.

**Comment by antonioandrade** [comment]
For reference, this update enables fetching data from the server with the latest Todos https://github.com/antonioandrade/SwiftDDP/commit/23cc42e67443667995bdbc52f615079eaded9d98
Since the _Todos_ methods have changed so much, other functions probably remain broken.

**Comment by siegesmund** [comment]
Hmm. I haven't followed the updates to the Todos app, so I'll have to review those.

**Comment by siegesmund** [comment]
Ok, I've had a look at it. I don't think it'll be hard to update, but it will take a little time. Allow/Deny rules were always confusing, and they're now out of favor it seems, so whereas in the past insert, update etc. were Mongo collection methods with access controlled by the allow/deny api, now they're explicitly defined regular methods. So, instead of using using collection.insert, we'll need to use the Meteor.call api. 

You've made a few changes already, so if you make a pull request, I'll merge those.

**Comment by siegesmund** [comment]
Yea, you're right. It's changed a lot. it looks like they're wrapped the Mongo collection methods in regular methods with simple schema validation. Still looking it over, but if you want to create a pull request, I'll merge your changes.

**Comment by antonioandrade** [comment]
Hey @siegesmund. Thanks for the #41 merge (though it doesn't bring us very far).

I've digged in some more and came up with a couple of thoughts:
- They really seem to have changed to method naming. To make List inserts work, I made this change https://github.com/antonioandrade/SwiftDDP/commit/70aa11126f82f86e7a05d19b656d23303b9bd304. This makes me question whether SwiftDDP is making assumptions too deeply? I mean, the dot-slash notation. I might be missing part of the protocol though.
- I don't really understand why this line https://github.com/meteor/todos/blob/master/imports/api/lists/methods.js#L15 reads `new SimpleSchema({}).validator()` instead of `Lists.schema.validator()`. Making this change allows List inserts to work, properly validated, considering the point above. Thoughts?

Cheers

**Comment by siegesmund** [comment]
Thanks for putting some thought into this. 

I don't think that changing the name of the method on insert is the way to go. 

The way I read it is this: When you use a client-side collection inserts, updates etc. (mini mongo for example), the collection insert/update/delete api is actually a wrapper around a regular Meteor method. That's what you saw, and what you changed in @70aa111. Changing this might make it work in this instance, but it will break inserts in every other instance.

The meteor collection api is secured using Allow/Deny rules, but Allow/Deny rules have fallen out of favor because they're confusing and easy to misconfigure. It's also hard to validate inputs. Thus, a better practice is to use plain Meteor methods and implement your authorization logic explicitly. That's what they've done here. So to access them, we need to use Meteor.call instead of Collection.insert.

Regarding your second question. It's `new SimpleSchema({}).validator()` because you're using SimpleSchema to merely validate the _method arguments_ against the object you pass, rather than validating a document against the collection/document schema. So,  `new SimpleSchema({}).validator()` indicates that it should not accept any arguments, whereas `new SimpleSchema({
    listId: { type: String },
    newName: { type: String },
  }).validator()` indicates that it should accept two arguments of type string.

Thoughts?

**Comment by antonioandrade** [comment]
Hey @siegesmund. I now got most SwiftDDP aspects working on my original project so this was a good learning piece. It's a really nice library.

The first point makes sense. I might be pushing some more updates to the example in that direction.

In regards to the validation point, though I believe I correctly got the concept, I still think my change makes most sense: new Lists should at least require a `name` and `incompleteCount` (the List schema), instead of validating the non-existence of arguments, right? Otherwise I get the error `keyNotInSchema` error below: 

````
[Debug] [DDP] [0x7fef906f6d80] [260] ddpMessageHandler > Received message: {
    error =     {
        details =         (
                        {
                details =                 {
                    value = asassasaassasasa;
                };
                name = name;
                type = keyNotInSchema;
            },
                        {
                details =                 {
                    value = 0;
                };
                name = incompleteCount;
                type = keyNotInSchema;
            }
        );
        error = "validation-error";
        errorType = "Meteor.Error";
        message = "name is not allowed by the schema [validation-error]";
        reason = "name is not allowed by the schema";
    };
    id = C01640B20F0f48D8900E890863045794;
    msg = result;
}
````

**Comment by siegesmund** [comment]
To be honest, I don't really understand why they've done it that way either. It looks sort of unfinished to me, unless they just wanted to demonstrate the way to validate no arguments. You could open an issue on the repo and ask/suggest a change :).

Meteor has been changing a lot lately, and I don't have as much time as I'd like to keep the examples up to date, so thanks for putting so much thought into this.

**Comment by siegesmund** [comment]
Ended up removing the examples; not enough time to keep them up to date with the changes to Meteor.
