### ISSUE TITLE
How to observe for Meteor connection

### ISSUE THREAD

**Issue by PIRDev** [siegesmund/SwiftDDP#55]
Hi, how can I know when the Meteor connection is connected or disconnected?

**Comment by siegesmund** [comment]
When you [pass a callback to the connection method](https://github.com/siegesmund/SwiftDDP#connecting-to-a-meteor-server) that callback is executes after the server sends a successful connection message. That's how you know when it's connected.

Disconnection is trickier. There is no DDP message for 'disconnect'. Rather, the client and server may exchange pings to make sure that one another are still there. If too long an interval passes without receiving a ping response, the server will close the connection.

If the connection closes, SwiftDDP automatically tries reestablish the connection. This is analogous to the way DDP works in the browser (MeteorJS). The connection is designed to happen in the background, independent of the application code,  and to be managed by the server.

So, for the initial connection, use the callback. As for disconnection, it should not happen unless your server refuses the connection because it can no longer reach your client.

**Comment by PIRDev** [comment]
Thank you for the quick reply. However, what I need in my application is to deactivate users' interactions when meteor is disconnected and reactivate when it's reconnected. Therefore, the call back function after calling "connect" is only useful if I connect to meteor manually, but I need to handle the auto-reconnect as well.

Is there a way to listen to onConnect and onDisconnect?

**Comment by siegesmund** [comment]
Did you read the reply above?

**Comment by siegesmund** [comment]
Closing this... please reopen or open a new issue of this isn't clear.
