### ISSUE TITLE
Can login and get data from publications with user validation but cannot call methods with user validation

### ISSUE THREAD

**Issue by wkniffin** [siegesmund/SwiftDDP#56]
Hello,

I have been running into issues when calling Meteor methods. I am able to connect to the client and login, and I receive a login token. I am able to subscribe to various subscriptions. However when I attempt to call methods I get denied by my validation which is setup as follows (which works for web client):
```javascript
export const insert = new ValidatedMethod({
  name: 'examples.insert',
  validate: new SimpleSchema({
    name: { type: String, max: 80 },
  }).validator(),
  run({ name, exampleDescription }) {
    if (!this.userId) {
      throw new Meteor.Error('examples.insert.accessDenied',
        'You must be logged in to insert an example!');
    }
  ...
  },
});
```
**Here is the catch**: I only get denied when I have freshly installed the app on my phone/simulator and I run it for the first time - so I know the method calls work in some cases.

Here is the snippet for connection and login:
```swift
Meteor.client.allowSelfSignedSSL = true
        Meteor.client.logLevel = .Warning
        let url = my valid websocket
        Meteor.connect(url){
            print("Connected to websocket...")
            Meteor.loginWithPassword(my username, password: my password){ result, error in
                print("Logging into client...")
                print(result)
                print(error)
```
Methods are being called using Meteor.call

**Comment by siegesmund** [comment]
It's hard to tell with just the info you've provided, but it sounds like you may be calling the method before the login has completed. Logins are persisted across sessions, so that may explain why it works after failing on a new app install. Are you/have you tried explicitly logging out and calling the method; logging out and restarting the app, etc?

**Comment by jeffmaynard** [comment]
I thought that would be the case, (referring to calling the method before login has completed) however these are the reasons why I ruled that out. On a new app install, I receive a token and all of my subscriptions are loaded properly. I can even sit there for a few minutes on the off chance the login wasn't completed, and it would still fail on method call. If I try to logout at that point, logout fails saying that the user is nil. I have tried explicitly logging out and calling the method and essentially everything that I do in that fresh install run (in terms of method calls) in unsuccessful. After restarting the app everything works perfectly.

**Comment by siegesmund** [comment]
Ok, to be clear, the authentication error you're seeing is on the server? 

If this is the case, it seems that under some conditions, the client is not passing the correct credentials to the server. The question is why. Could you post some working iOS code that I could take a look at?

**Comment by siegesmund** [comment]
There's not much I can do if I can't reproduce the problem. I'd suggest you remove ALL of the Meteor stuff except the login and the method call, and go from there.

**Comment by siegesmund** [comment]
I just saw your edit above. Glad it's working for you!

**Comment by jeffmaynard** [comment]
I have actually solved the issue though! Once I realized that 'applicationWillResignActive' was calling when I didn't expect it to (I have growing, but limited knowledge of Swift/iOS conventions) I removed the unneeded Meteor.logout() function and everything began to work as expected. I had even forgotten that I put the Meteor.logout() function in there, which is why I didn't think of it earlier when I was troubleshooting. Thanks again for your prompt replies. **Note for anyone reading:** don't attempt to logout during applicationWillResignActive unless you also unwind to a point where a user can log in again!
